// Generated by CoffeeScript 1.4.0
(function() {
  var addTransport, contains, debug, disable, enable, error, isTransportValid, logKeys, logLevel, logLevels, removeTransport, scream, setKeys, setLevel, speech, talk, transports, verbosityLevels, warn, whisper, _error, _log, _warn,
    __slice = [].slice;

  logLevels = {
    debug: 2,
    warn: 4,
    error: 8
  };

  logLevel = logLevels.debug;

  logKeys = {};

  verbosityLevels = {
    whisper: 2,
    talk: 4,
    speech: 8,
    scream: 16
  };

  enable = function(key) {
    return logKeys[key] = new RegExp(key);
  };

  disable = function(key) {
    return delete logKeys[key];
  };

  setLevel = function(lvl) {
    if (logLevels.hasOwnProperty(lvl)) {
      return logLevel = logLevels[lvl];
    }
  };

  setKeys = function(keys) {
    var key, _i, _len, _results;
    if (keys == null) {
      keys = [];
    }
    keys = keys instanceof Array ? keys : [keys];
    _results = [];
    for (_i = 0, _len = keys.length; _i < _len; _i++) {
      key = keys[_i];
      _results.push(enable(key));
    }
    return _results;
  };

  transports = [];

  contains = function(ary, item) {
    var x, _i, _len;
    for (_i = 0, _len = ary.length; _i < _len; _i++) {
      x = ary[_i];
      if (item === x) {
        return true;
      }
    }
    return false;
  };

  isTransportValid = function(logger) {
    return (logger.log instanceof Function) && (logger.warn instanceof Function) && (logger.error instanceof Function);
  };

  addTransport = function(logger) {
    if (isTransportValid(logger)) {
      if (!contains(transports, logger)) {
        return transports.push(logger);
      }
    } else {
      throw {
        error: 'invalid_transport',
        description: 'must have .log, .warn, and .error function.'
      };
    }
  };

  addTransport(console);

  removeTransport = function(logger) {
    var i, x, _i, _len, _results;
    _results = [];
    for (i = _i = 0, _len = transports.length; _i < _len; i = ++_i) {
      x = transports[i];
      if (logger === x) {
        _results.push(transports.splice(i, 1));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  _log = function() {
    var args, trans, _i, _len, _results;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = transports.length; _i < _len; _i++) {
      trans = transports[_i];
      _results.push(trans.log.apply(trans, args));
    }
    return _results;
  };

  _warn = function() {
    var args, trans, _i, _len, _results;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = transports.length; _i < _len; _i++) {
      trans = transports[_i];
      _results.push(trans.warn.apply(trans, args));
    }
    return _results;
  };

  _error = function() {
    var args, trans, _i, _len, _results;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = transports.length; _i < _len; _i++) {
      trans = transports[_i];
      _results.push(trans.error.apply(trans, args));
    }
    return _results;
  };

  debug = function() {
    var args, k, key, regex, _results;
    key = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (logLevel <= logLevels.debug) {
      _results = [];
      for (k in logKeys) {
        regex = logKeys[k];
        if (key.match(regex)) {
          _log('DEBUG ----------', key);
          _results.push(_log(JSON.stringify(args, null, 2)));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  };

  whisper = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  };

  talk = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  };

  speech = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  };

  scream = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return _log.apply(null, args);
  };

  warn = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (logLevel <= logLevels.warn) {
      _warn("*** WARN START ***");
      _warn.apply(null, args);
      return _warn("*** WARN END   ***");
    }
  };

  error = function() {
    var arg, args, _i, _len;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (logLevel <= logLevels.error) {
      _error('****** ERROR START ******');
      _error.apply(null, args);
      for (_i = 0, _len = args.length; _i < _len; _i++) {
        arg = args[_i];
        if (arg != null ? arg.stack : void 0) {
          _error(arg.stack);
        }
      }
      return _error('****** ERROR END   ******');
    }
  };

  module.exports = {
    addTransport: addTransport,
    removeTransport: removeTransport,
    setLevel: setLevel,
    enable: enable,
    disable: disable,
    setKeys: setKeys,
    debug: debug,
    warn: warn,
    error: error,
    log: _log,
    whisper: whisper,
    talk: talk,
    speech: speech,
    scream: scream
  };

}).call(this);
